apiVersion: v1
kind: ServiceAccount
metadata:
  name: aad-pod-id-nmi-service-account
  namespace: aad-pod-identity

---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: nmi-allow-host-network-and-path
spec:
  seLinux:
    rule: RunAsAny
  privileged: true
  allowedCapabilities:
    - NET_ADMIN
  volumes:
    - hostPath
    - secret
  hostNetwork: true
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  allowedHostPaths:
    - pathPrefix: /run/xtables.lock
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:nmi-allow-host-network-and-path
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - nmi-allow-host-network-and-path
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: default:nmi-allow-host-network-and-path
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:nmi-allow-host-network-and-path
subjects:
- kind: Group
  name: system:nodes
  apiGroup: rbac.authorization.k8s.io
- kind: ServiceAccount
  name: aad-pod-id-nmi-service-account
  namespace: aad-pod-identity
